data_config:
  train_dir: /data/guangchen_li/datasets/amazon/train.pkl
  valid_dir: /data/guangchen_li/datasets/amazon/dev.pkl
  test_dir: /data/guangchen_li/datasets/amazon/test.pkl
  data_format: pkl
  data_specs:
    num_event_types: 16
    pad_token_id: 16
    padding_side: right
    truncation_side: right
    padding_strategy: null
    truncation_strategy: null
    max_len: null
base_config:
  stage: train
  backend: torch
  dataset_id: amazon
  runner_id: std_tpp
  model_id: AttNHP
  base_dir: ./checkpoints/
  specs:
    log_folder: ./checkpoints/1300514_139864610047808_251204-184628
    saved_model_dir: ./checkpoints/1300514_139864610047808_251204-184628/models/saved_model
    saved_log_dir: ./checkpoints/1300514_139864610047808_251204-184628/log
    output_config_dir: ./checkpoints/1300514_139864610047808_251204-184628/AttNHP_train_output.yaml
model_config:
  rnn_type: LSTM
  hidden_size: 16
  time_emb_size: 4
  num_layers: 2
  sharing_param_layer: false
  loss_integral_num_sample_per_step: 10
  dropout_rate: 0.0
  use_ln: false
  thinning:
    num_seq: 2
    num_sample: 1
    num_exp: 50
    look_ahead_time: 10
    patience_counter: 5
    over_sample_rate: 5
    num_samples_boundary: 5
    dtime_max: 5
    num_step_gen: 1
  num_event_types_pad: 17
  num_event_types: 16
  event_pad_index: 16
  model_id: AttNHP
  pretrained_model_dir: null
  gpu: 0
  model_specs: {}
trainer_config:
  seed: 2019
  gpu: 0
  batch_size: 256
  max_epoch: 100
  shuffle: false
  optimizer: adam
  learning_rate: 0.001
  valid_freq: 1
  use_tfb: false
  metrics:
  - acc
  - rmse
